### ISSUE TITLE
Script Rename

### ISSUE THREAD

**Issue by chadfawcett** [chadfawcett/NodeMailForm#1]
Script needs a better name than NodeMailForm.

**Comment by jonotron** [comment]
Ideas (all are available on npm):

* mailstick
* deliverist
* static-mailer

**Comment by chadfawcett** [comment]
@jonotron Thanks for the suggestions! I like the simplicity of static-mailer but it kind of makes the script sound static. Not sure.

What do you think of form-emailer? Looks to be available on npm.

**Comment by jonotron** [comment]
form-emailer is *ok* I guess.

**Comment by chadfawcett** [comment]
@jonotron tell me how you really feel.

**Comment by jonotron** [comment]
I like this new name. Who came up with it?

**Comment by chadfawcett** [comment]
It just randomly popped into my head when I looked at this issue again. I think your suggestion of *mailstick* led me in the direction, but I thought I'd prefer an animal name. I'm a fan of dogs so I wen't with hound.
