### ISSUE TITLE
Allow ad-hoc form fields in the email message

### ISSUE THREAD

**Issue by jonotron** [chadfawcett/NodeMailForm#13]
Ex: I often want a phone number as an optional form field in my contact forms. I would be nice to have this included in the email message.

It would be easy enough to add some basic hard coded fields (like `phone`) but it might be useful to have additional fields that get automatically included in the message.

**Comment by jonotron** [comment]
One idea I had was to allow the form to define the fields in a conventional way.

e.g. if you had the following in your form

```html
<input type="text" name="_fields.address" />
```

The following would be added to the email:

```
address: Some address the user typed
```

## Another idea is to allow formatting options

```html
<input type="text" name="_fields.address.value" />
<input type="hidden" name="_fields.address.title" value="The Address" />
```

The the email would be parsed and sent as:

```
The Address: Some address the user typed
```

This seems a bit overkill perhaps.

**Comment by chadfawcett** [comment]
@jonotron I like the idea. Your first suggestion seems pretty straightforward and light. As you're aware this project was meant to be light and was to use. Your second suggestion might be nice but it feels like it might add too much complexity to it. Then again, it would be an optional form field that the average user would not have to use.

I would say for now, it would be nice to implement to first suggestion. You can make a pull request with your implementation if you would like. Or I can get to it in a few days.

**Comment by chadfawcett** [comment]
@jonotron One solution to the title field would be to use camel case variables for the field name.

So `name="_fields.theAddress"` would be automatically parsed as `The Address`.

**Comment by jonotron** [comment]
@chadfawcett CamelCase is better and simpler! I might whip up a PR in a few days for the arbitrary case (without the camelCase stuff)
